### ISSUE TITLE
how to add images to pages?

### ISSUE THREAD

**Issue by KissBalazs** [FrozenPandaz/ng-universal-demo#13]
I have a problem with inserting images to the pages. 

For instance:
` <img src="../../assets/img/mylogo.png" />`

and with existing path and file, it gives me a 404 error:
`(index):10 GET http://localhost:8000/assets/img/mylogo.png 404 (Not Found)`

Same for 
`<img [src]="logoPath"/>, etc. `

Thank you for the help in advance.

**Comment by KissBalazs** [comment]
This is a webpack issue, need to export the assets folder. How silly of me...

**Comment by Dragons0458** [comment]
Hi, sorry, but ... how can I fix the error? I'm having the same problem... Thank you!

**Comment by ysus** [comment]
https://github.com/FrozenPandaz/ng-universal-demo/issues/22
