### ISSUE TITLE
How can you access location/url information on the server angular app

### ISSUE THREAD

**Issue by rlavoie** [FrozenPandaz/ng-universal-demo#18]
How can I get access to what would have been window.location.host and window.location.pathname on the server within my angular app? I have seen provider examples just cant seem to grasp it or get anything working.

**Comment by FrozenPandaz** [comment]
You can get it from the Request object. It is available from the REQUEST injection token

https://github.com/angular/universal/blob/master/modules/ng-express-engine/README.md#using-the-request-and-response

**Comment by rlavoie** [comment]
@FrozenPandaz I have seen that but unsure where/how to inject that so my app.component can read the headers.

**Comment by rlavoie** [comment]
I was able to solve this with the REQUEST token as you suggested. I needed to inject with the injector, because I was getting a client side error.

import { REQUEST } from '@nguniversal/express-engine/tokens';
import { Injector } from '@angular/core';

ngOnInit() {

    if (isPlatformBrowser(this.platformId)) {
      this.domainName = window.location.host + window.location.pathname;
    }else if(isPlatformServer(this.platformId)){
      const req = this.injector.get(REQUEST);
      this.domainName = req.headers['host'] + req.originalUrl;
    }

    console.log(this.domainName)

  }
