### ISSUE TITLE
Error compiling Scss with npm run build:aot

### ISSUE THREAD

**Issue by rlavoie** [FrozenPandaz/ng-universal-demo#21]
When trying to run npm run build:aot, I get an error if a component references a scss file instead of css.

 ERROR in ./src/ngfactory/app/components/app/app.component.scss.ngstyle.ts
    Module build failed: Invalid CSS after "...lint:disable */": expected 1 selector or at-rule, was "export const styles"

// Added to webpack.common.js
{
            test: /\.scss/,
            use: [
                { loader: 'raw-loader' },
                { loader: 'sass-loader' }
            ]
        }

**Comment by ysus** [comment]
i think your test must be > `test: /\.scss$/,`
